config/routes.rb
MasterHours::Application.routes.draw do
  root "home#index"
  devise_for :users

  resources :projects do
    resources :work_days
    get "chart/show"
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :work_days

  validates :name, presence: true

  def total_minutes
    work_days.sum(:minutes)
  end

  def total_hours
    total_minutes/60.0
  end

  def total_score
    (multiply * total_minutes).to_i
  end

  def all_data
    data = []
    begin_time = work_days.first.time
    end_day = Timw.now

    day = nil
    while begin_time < end_day
      work_days.each do | i |
        if i.time.year == begin_time.year && i.time.month == begin_time.month && i.time.day == begin_time.day
          day = i
          break;
      end
      end

      data << {date: begin_time.to_date.to_s, score: 0, hours: day ? day.minutes/60.0:0}
      begin_time = begin_time + 1.day
    end
    data
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/models/work_day.rb
class WorkDay < ActiveRecord::Base
  default_scope order('time')

  belongs_to :project
  validates :time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chart_controller.rb
class ChartController < ApplicationController
  before_filter :load_project

  def show
    respond_to do |format|
      format.js
    end
  end

  private
  def load_project
    @project = current_user.projects.find params[:project_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def show
    @project = current_user.projects.find params[:id]
  end
end

app/controllers/work_days_controller.rb
class WorkDaysController < ApplicationController
  before_filter :authenticate_user!

  def index
  end

  def update

  end

  def create
  end

  def show
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/chart/show.js.erb
new Morris.Line({
    element: 'chart',
    // Chart data records -- each entry in this array corresponds to a point on
    // the chart.
    data: [
    { year: '2008', time: 20 },
    { year: '2009', time: 10 },
    { year: '2010', time: 5 },
    { year: '2011', time: 5 },
    { year: '2012', time: 20 }
    ],
    // The name of the data record attribute that contains x-values.
    xkey: 'year',
    // A list of names of data record attributes that contain y-values.
    ykeys: ['time'],
    // Labels for the ykeys -- will be displayed when you hover over the
    // chart.
    labels: ['时间']
  });

app/views/home/index.html.erb
<div class="container">
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MasterHours</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- bootstrap begin -->
  <link rel="stylesheet" href="http://lib.sinaapp.com/js/bootstrap/v3.0.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="http://lib.sinaapp.com/js/bootstrap/v3.0.0/css/bootstrap-theme.min.css">
  <script src="http://lib.sinaapp.com/js/bootstrap/v3.0.0/js/bootstrap.min.js"></script>
  <!-- bootstrap end -->

</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Master Hours</a>
      </div>
      <div class="navbar-collapse collapse">
        <% if !user_signed_in? %>
          <%= form_for(User.new, :url => user_session_path, :html => {class: "navbar-form navbar-right"}) do |f| %>
            <div class="form-group">
              <%= f.email_field :email, :autofocus => true, placeholder: "邮箱", class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, placeholder: "密码", class: "form-control" %>
            </div>
            <button type="submit" class="btn btn-success">登录</button>
            <%= link_to "注册", new_user_registration_path, class: "btn btn-success" %>
          <% end %>
        <% end  %>
      </div><!--/.navbar-collapse -->
    </div>
  </div>

  <br />
  <br />
  <br />

  <!-- alert and notice begin -->
  <% if flash[:alert].present? %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>错误!</h4>    <strong><%= flash[:alert]%></strong>
    </div>
  <% end %>
  <% if flash[:notice].present? %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">×</button>
      <h4>通知!</h4>    <strong><%= flash[:notice]%></strong>
    </div>
  <% end %>
  <!-- alert and notice end-->

  <%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<div class="container">
  <ol>
  <% @projects.each do |project|%>
    <li> <%= link_to project.name, project_path(project) %> </li>
  <% end %>
</ol>
</div>

app/views/projects/show.html.erb
<div class="container">
  你花费的总时间:<%= @project.total_hours %>
<div id="chart"></div>

<div class="well">
  <div id="datetimepicker4" class="input-append">
    <input data-format="yyyy-MM-dd" type="text"></input>
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar"></i>
    </span>
  </div>
</div>

</div>

<script>
  $(document).ready(function(){
    $.ajax({
      type: "GET",
      url: "<%= project_chart_show_path(@project) %>",
    });


    $('#datetimepicker4').datetimepicker({
      pickTime: false
    });
  });
</script>

app/views/work_days/index.html.erb
<h1>WorkDays#index</h1>
<p>Find me in app/views/work_days/index.html.erb</p>

app/views/work_days/show.html.erb
<h1>WorkDays#show</h1>
<p>Find me in app/views/work_days/show.html.erb</p>